

GET /list HTTP/1.1
Host: localhost:8081
Cache-Control: no-cache

###
POST /task HTTP/1.1
Host: localhost:8081
Content-Type: application/json
Cache-Control: no-cache

{
	"task" : "Treti"
}

###
PUT /task/0 HTTP/1.1
Host: localhost:8081
Content-Type: application/json
Cache-Control: no-cache

{
	"task" : "X"
}

###
DELETE /task/0 HTTP/1.1
Host: localhost:8081
Content-Type: application/json
Cache-Control: no-cache

{}




